---
title: "Fixed effects modelling"
output: html_document
date: "2024-04-05"
---

```{r setup}
library(plm)
library(ggpubr)
library(latex2exp)
```


```{r plot chosen predictor variables (fig 6.10)}
#Renaming for legend
panel <- panel |> rename(Site=site)

# Assigning alpha values to try and make other sites more visible
panel$alpha_val <- c(1)
panel <- within(panel, alpha_val[code == 'DUNM'] <- c(0.00005))
panel <- within(panel, alpha_val[code == 'DUN7'] <- c(0.1))
panel <- within(panel, alpha_val[code == 'DUN6'] <- c(0.3))
panel <- within(panel, alpha_val[code == 'DUN5'] <- c(0.5))
panel <- within(panel, alpha_val[code == 'DUN4'] <- c(0.7))

#Create scatter plots of each predictor against NOx, add smoothing to help illustrate and possible relationship
ws_g<-ggplot(data=panel, aes(x=ws, y=nox))+
  geom_point(aes(color=Site, alpha=alpha_val))+
  theme_classic() +
  theme(legend.position="none") +
  scale_alpha(guide = 'none') +
  ggtitle("Wind Speed") +
  ylab(TeX(r'($NO_x$, $\mu$g/$m^3$)')) +
  xlab(TeX(r'(Speed, $ms^{-1}$)')) +
  geom_smooth() +
  scale_y_continuous(trans = "log")


air_g<-ggplot(data=panel, aes(x=air_temp, y=nox))+
  geom_point(aes(color=Site, alpha=alpha_val))+
  theme_classic() +
  theme(legend.position="none") +
  scale_alpha(guide = 'none') +
  ggtitle("Air Temperature") +
  ylab(TeX(r'($NO_x$, $\mu$g/$m^3$)')) +
  xlab(TeX(r'(Temperature, $^{\circ}C$)')) +
  geom_smooth() +
  scale_y_continuous(trans = "log")

wd_g<-ggplot(data=panel, aes(x=wd, y=nox))+
  geom_point(aes(color=Site, alpha=alpha_val))+
  theme_classic() +
  theme(legend.position="none") +
  scale_alpha(guide = 'none') +
  ggtitle("Wind Direction") +
  ylab(TeX(r'($NO_x$, $\mu$g/$m^3$)')) +
  xlab(TeX(r'(Bearing, degrees)')) +
  geom_smooth() +
  scale_y_continuous(trans = "log")

#Combine all plots together into a grid
pred_plot <-ggarrange(ws_g,air_g,wd_g, ncol=3, nrow=1, common.legend = TRUE, legend="bottom")
#Add title
annotate_figure(pred_plot, top = text_grob("Potential predictor variables",face="bold", size=18))
```

```{r create fixed effects model}
# Creating fixed effects model. 'wd' not included in final model, kept here as an example
# of an insignificant predictor which was discarded for final model
fixed <- plm(nox ~  trend + season1 + ws + air_temp + wd, data=panel, index=c("site", "date"), model="within") 
```


```{r initial summary (table 6.1)}
# Note t val of 'wd' showing its statistical insignificance
summary(fixed)
```

```{r summary of difference in means (table 6.2)}
summary(fixef(fixed, type = "dmean"))
```


``` {r individual models for each site}
# Exactly the same model set up but for each individual site
summary(plm(nox ~ trend + season1 + ws + wd + air_temp, data=panel |> filter(code=="DUN4"), index=c("site", "date"), model="within"))

summary(plm(nox ~ trend + season1 + ws + wd + air_temp, data=panel |> filter(code=="DUN6"), index=c("site", "date"), model="within"))

summary(plm(nox ~ trend + season1 + ws + wd + air_temp, data=panel |> filter(code=="DUN1"), index=c("site", "date"), model="within"))

summary(plm(nox ~ trend + season1 + ws + wd + air_temp, data=panel |> filter(code=="DUNM"), index=c("site", "date"), model="within"))

summary(plm(nox ~ trend + season1 + ws + wd + air_temp, data=panel |> filter(code=="DUN5"), index=c("site", "date"), model="within"))

summary(plm(nox ~ trend + season1 + ws + wd + air_temp, data=panel |> filter(code=="DUN7"), index=c("site", "date"), model="within"))
```
